apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-demo-app
  labels:
    app: devops-demo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-demo-app
  template:
    metadata:
      labels:
        app: devops-demo-app
    spec:
      containers:
        - name: devops-demo-app
          image: alexb00/devops-demo-app:latest
          ports:
            - containerPort: 5000
