apiVersion: v1
kind: Service
metadata:
  name: devops-demo-app
spec:
  selector:
    app: devops-demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007
  type: NodePort
